/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Edit src/main.ts, then run npm run build in this plugin directory.
*/
"use strict";

const { Notice, Plugin, PluginSettingTab, Setting } = require("obsidian");

const DEFAULT_SETTINGS = {
  statePath: ".criv/state.json",
};

let wasmModule = null;

async function summarizeState(raw) {
  const wasm = await loadWasm();
  if (wasm) {
    return wasm.summarize_state(raw);
  }

  const state = JSON.parse(raw);
  return {
    schema: state.schema,
    node_count: Array.isArray(state.graph?.nodes) ? state.graph.nodes.length : 0,
    edge_count: Array.isArray(state.graph?.edges) ? state.graph.edges.length : 0,
    source_count: Array.isArray(state["source-index"]) ? state["source-index"].length : 0,
    pattern_count: Array.isArray(state["registered-patterns"]) ? state["registered-patterns"].length : 0,
    first_node_id: state.graph?.nodes?.[0]?.id,
    first_edge: state.graph?.edges?.[0]
      ? `${state.graph.edges[0].from}:${state.graph.edges[0].kind}:${state.graph.edges[0].to}`
      : undefined,
    first_source_path: state["source-index"]?.[0]?.path,
  };
}

async function loadWasm() {
  if (!wasmModule) {
    wasmModule = import("./pkg/criv_wasm.js").catch(() => null);
  }
  return wasmModule;
}

class CrivPlugin extends Plugin {
  async onload() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.addRibbonIcon("network", "criv status", async () => this.showStatus());
    this.addCommand({
      id: "show-criv-status",
      name: "Show criv status",
      callback: async () => this.showStatus(),
    });
    this.addSettingTab(new CrivSettingTab(this.app, this));
  }

  async showStatus() {
    const state = await this.readState();
    if (!state) {
      new Notice(`criv state is missing at ${this.settings.statePath}`);
      return;
    }

    new Notice(
      `criv ${state.schema}: ${state.node_count} nodes, ${state.edge_count} edges, ${state.source_count} source files`
    );
  }

  async readState() {
    try {
      const raw = await this.app.vault.adapter.read(this.settings.statePath);
      return await summarizeState(raw);
    } catch {
      return null;
    }
  }

  async saveSettings() {
    await this.saveData(this.settings);
  }
}

class CrivSettingTab extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }

  display() {
    const { containerEl } = this;
    containerEl.empty();

    new Setting(containerEl)
      .setName("State path")
      .setDesc("Path to the criv watcher state file, relative to the vault root.")
      .addText((text) =>
        text
          .setPlaceholder(".criv/state.json")
          .setValue(this.plugin.settings.statePath)
          .onChange(async (value) => {
            this.plugin.settings.statePath = value.trim() || DEFAULT_SETTINGS.statePath;
            await this.plugin.saveSettings();
          })
      );
  }
}

module.exports = CrivPlugin;
