use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use clap::{Args as ClapArgs, Subcommand};
use serde::{Deserialize, Serialize};

use crate::config::Config;
use crate::git;
use crate::util::{remove_file_in, walk_files, write_atomic_in};
use crate::vault::Vault;
use crate::{CrivError, Result};

#[derive(Debug, ClapArgs)]
pub(crate) struct AdrOptions {
    #[command(subcommand)]
    command: AdrCommand,
}

#[derive(Debug, Subcommand)]
enum AdrCommand {
    /// Reconcile provisional ADR IDs against an integration target.
    Reconcile(ReconcileOptions),
}

#[derive(Debug, ClapArgs)]
struct ReconcileOptions {
    /// Target branch or commit to compare with.
    #[arg(long)]
    base: String,
    /// Report a required reconciliation without modifying the worktree.
    #[arg(long)]
    check: bool,
}

#[derive(Debug, Clone, Eq, PartialEq)]
struct AdrFile {
    path: String,
    id: u32,
    slug: String,
    contents: String,
}

#[derive(Debug, Clone)]
struct ReconcilePlan {
    base_ref: String,
    target_sha: String,
    merge_base: String,
    mappings: Vec<Mapping>,
    branch_adrs: Vec<AdrFile>,
}

#[derive(Debug, Clone, Eq, PartialEq, Serialize, Deserialize)]
struct Mapping {
    old_id: u32,
    new_id: u32,
    old_path: String,
    new_path: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct Receipt {
    schema: String,
    base_ref: String,
    target_sha: String,
    merge_base: String,
    mappings: Vec<Mapping>,
    files: Vec<ReceiptFile>,
}

#[derive(Debug, Serialize, Deserialize)]
struct ReceiptFile {
    path: String,
    after_hash: String,
}

pub(crate) fn run(root: &Path, options: AdrOptions) -> Result<()> {
    match options.command {
        AdrCommand::Reconcile(options) => reconcile(root, options),
    }
}

/// CI calls the same read-only planner as the user-facing `--check` command.
pub(crate) fn check_base(root: &Path, base_ref: &str) -> Result<()> {
    reconcile(
        root,
        ReconcileOptions {
            base: base_ref.to_owned(),
            check: true,
        },
    )
}

/// Local hooks accept only a staged rename whose destination exactly matches a
/// receipt generated by this command.
pub(crate) fn receipt_allows_rename(root: &Path, old_path: &str, new_path: &str) -> bool {
    let Ok(receipt) = read_receipt(root) else {
        return false;
    };
    if receipt.schema != "criv.adr-reconcile/1"
        || !git::ref_is_stable(root, &receipt.base_ref, &receipt.target_sha).unwrap_or(false)
        || !receipt
            .mappings
            .iter()
            .any(|mapping| mapping.old_path == old_path && mapping.new_path == new_path)
    {
        return false;
    }
    let Some(file) = receipt.files.iter().find(|file| file.path == new_path) else {
        return false;
    };
    git::blob(root, ":", new_path)
        .map(|contents| hash(&contents) == file.after_hash)
        .unwrap_or(false)
}

fn reconcile(root: &Path, options: ReconcileOptions) -> Result<()> {
    if !git::is_repository(root)? {
        return Err(CrivError::new(
            "`criv adr reconcile` requires a Git worktree",
        ));
    }
    let target_sha = git::resolve_commit(root, &options.base)?;
    let plan = build_plan(root, &options.base, &target_sha)?;
    println!("ADR reconciliation target: {}", plan.target_sha);
    if plan.mappings.is_empty() {
        println!("ADR allocation is current; no reconciliation is required");
        return Ok(());
    }
    print_mapping(&plan.mappings);
    if options.check {
        return Err(CrivError::new(format!(
            "ADR allocation conflicts with target {}; run `criv adr reconcile --base {}`",
            plan.target_sha, options.base
        )));
    }
    let dirty = git::dirty_paths(root)?;
    if !dirty.is_empty() {
        return Err(CrivError::new(format!(
            "refusing to reconcile a dirty worktree; commit or stash: {}",
            dirty.join(", ")
        )));
    }
    if !git::ref_is_stable(root, &options.base, &plan.target_sha)? {
        return Err(CrivError::new(format!(
            "target ref `{}` moved since it resolved to {}; retry reconciliation",
            options.base, plan.target_sha
        )));
    }
    apply_plan(root, &plan)?;
    if !git::ref_is_stable(root, &options.base, &plan.target_sha)? {
        return Err(CrivError::new(format!(
            "target ref `{}` moved during reconciliation; do not merge and retry against its new SHA",
            options.base
        )));
    }
    println!("ADR reconciliation applied; validate and commit the generated rename before merging");
    Ok(())
}

fn build_plan(root: &Path, base_ref: &str, target_sha: &str) -> Result<ReconcilePlan> {
    let vault = Vault::load(root)?;
    let current_config = &vault.config;
    let target_config = if git::tree_paths(root, target_sha, "criv.toml")?
        .iter()
        .any(|path| path == "criv.toml")
    {
        Some(git::blob(root, target_sha, "criv.toml")?)
    } else {
        None
    };
    let target_config = Config::parse(target_config.as_deref())?;
    if current_config.docs_dir != target_config.docs_dir
        || current_config.adr_dir != target_config.adr_dir
    {
        return Err(CrivError::new(
            "refusing ADR reconciliation because vault.docs or vault.adr differs from the target; cannot prove ADR ownership",
        ));
    }
    let adr_prefix = format!("{}/{}/", vault.config.docs_dir, vault.config.adr_dir);
    let merge_base = git::merge_base(root, target_sha, "HEAD")?;
    let target_paths = git::tree_paths(root, target_sha, &adr_prefix)?;
    let merge_paths = git::tree_paths(root, &merge_base, &adr_prefix)?
        .into_iter()
        .collect::<BTreeSet<_>>();
    let target = target_paths
        .iter()
        .filter(|path| is_adr_path(&adr_prefix, path))
        .map(|path| {
            git::blob(root, target_sha, path).and_then(|contents| parse_adr(path, contents))
        })
        .collect::<Result<Vec<_>>>()?;
    ensure_unique(&target, "target")?;
    let target_by_id = target
        .iter()
        .map(|adr| (adr.id, adr))
        .collect::<BTreeMap<_, _>>();
    let target_paths = target_paths.into_iter().collect::<BTreeSet<_>>();

    let adr_root = root.join(&adr_prefix);
    let branch_adrs = walk_files(&adr_root, Some("md"))?
        .into_iter()
        .map(|path| {
            let relative = crate::util::strip_prefix(&path, root);
            Ok((relative, fs::read_to_string(path)?))
        })
        .collect::<Result<Vec<_>>>()?
        .into_iter()
        .filter(|(path, _)| is_adr_path(&adr_prefix, path) && !merge_paths.contains(path))
        .map(|(path, contents)| parse_adr(&path, contents))
        .collect::<Result<Vec<_>>>()?;
    ensure_unique(&branch_adrs, "branch-local")?;

    let target_max = target.iter().map(|adr| adr.id).max().unwrap_or(0);
    let conflicted = branch_adrs.iter().any(|adr| {
        target_paths.contains(&adr.path)
            || target_by_id
                .get(&adr.id)
                .is_some_and(|target| target.path != adr.path)
            || adr.id <= target_max
    });
    let mappings = allocation_mappings(&branch_adrs, target_max, conflicted)?;
    let destination_paths = mappings
        .iter()
        .map(|mapping| mapping.new_path.clone())
        .collect::<BTreeSet<_>>();
    if destination_paths.len() != mappings.len() {
        return Err(CrivError::new("ADR reconciliation destinations collide"));
    }
    for mapping in &mappings {
        if mapping.old_path != mapping.new_path
            && root.join(&mapping.new_path).exists()
            && !mappings
                .iter()
                .any(|other| other.old_path == mapping.new_path)
        {
            return Err(CrivError::new(format!(
                "ADR reconciliation destination `{}` already exists",
                mapping.new_path
            )));
        }
    }
    Ok(ReconcilePlan {
        base_ref: base_ref.into(),
        target_sha: target_sha.into(),
        merge_base,
        mappings,
        branch_adrs,
    })
}

fn allocation_mappings(
    branch_adrs: &[AdrFile],
    target_max: u32,
    conflicted: bool,
) -> Result<Vec<Mapping>> {
    if !conflicted {
        return Ok(Vec::new());
    }
    let mut ordered = branch_adrs.to_vec();
    ordered.sort_by_key(|adr| adr.id);
    let allocation_end = target_max
        .checked_add(ordered.len() as u32)
        .ok_or_else(|| CrivError::new("ADR ID allocation overflow"))?;
    if allocation_end > 9999 {
        return Err(CrivError::new(
            "ADR reconciliation allocation exceeds ADR-9999",
        ));
    }
    ordered
        .into_iter()
        .enumerate()
        .map(|(offset, adr)| {
            let new_id = target_max
                .checked_add(offset as u32 + 1)
                .ok_or_else(|| CrivError::new("ADR ID allocation overflow"))?;
            let new_name = filename(&new_id, &adr.slug);
            let parent = Path::new(&adr.path)
                .parent()
                .unwrap_or_else(|| Path::new(""));
            Ok(Mapping {
                old_id: adr.id,
                new_id,
                old_path: adr.path.clone(),
                new_path: parent.join(new_name).to_string_lossy().replace('\\', "/"),
            })
        })
        .collect()
}

fn is_adr_path(prefix: &str, path: &str) -> bool {
    path.starts_with(prefix) && path != format!("{prefix}README.md") && path.ends_with(".md")
}

fn parse_adr(path: &str, contents: String) -> Result<AdrFile> {
    let name = Path::new(path)
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| CrivError::new(format!("ADR path `{path}` is not valid UTF-8")))?;
    let stem = name
        .strip_suffix(".md")
        .ok_or_else(|| CrivError::new(format!("ADR `{path}` must be Markdown")))?;
    let (number, slug) = stem.split_once('-').ok_or_else(|| {
        CrivError::new(format!(
            "branch-local ADR `{path}` must use NNNN-kebab-title.md"
        ))
    })?;
    if number.len() != 4 || !number.bytes().all(|byte| byte.is_ascii_digit()) || slug.is_empty() {
        return Err(CrivError::new(format!(
            "branch-local ADR `{path}` has a malformed filename"
        )));
    }
    let id = number.parse::<u32>().unwrap();
    let normalized = contents.replace("\r\n", "\n");
    let frontmatter = normalized
        .strip_prefix("---\n")
        .and_then(|rest| {
            rest.split_once("\n---\n")
                .map(|(frontmatter, _)| frontmatter)
        })
        .ok_or_else(|| {
            CrivError::new(format!("branch-local ADR `{path}` has no YAML frontmatter"))
        })?;
    let expected_id = format!("ADR-{number}");
    let actual_id = frontmatter
        .lines()
        .find_map(|line| line.strip_prefix("id:").map(str::trim));
    if actual_id != Some(expected_id.as_str()) {
        return Err(CrivError::new(format!(
            "ADR `{path}` filename and frontmatter id must agree"
        )));
    }
    Ok(AdrFile {
        path: path.into(),
        id,
        slug: slug.into(),
        contents,
    })
}

fn ensure_unique(adrs: &[AdrFile], owner: &str) -> Result<()> {
    let mut ids = BTreeSet::new();
    for adr in adrs {
        if !ids.insert(adr.id) {
            return Err(CrivError::new(format!(
                "duplicate {owner} ADR ID ADR-{:04}",
                adr.id
            )));
        }
    }
    Ok(())
}

fn filename(id: &u32, slug: &str) -> String {
    format!("{id:04}-{slug}.md")
}

fn print_mapping(mappings: &[Mapping]) {
    println!("ADR reconciliation mapping:");
    for mapping in mappings {
        println!(
            "  ADR-{:04} -> ADR-{:04} ({})",
            mapping.old_id, mapping.new_id, mapping.new_path
        );
    }
}

fn apply_plan(root: &Path, plan: &ReconcilePlan) -> Result<()> {
    let rewrite_paths = rewrite_candidates(root, plan)?;
    let mut receipt_files = Vec::new();
    for (path, contents) in &rewrite_paths {
        write_atomic_in(root, Path::new("."), Path::new(path), contents)?;
        receipt_files.push(ReceiptFile {
            path: path.clone(),
            after_hash: hash(contents),
        });
    }
    for path in superseded_paths(&plan.mappings) {
        remove_file_in(root, Path::new("."), Path::new(path))?;
    }
    let errors = crate::check::validate_all(root)?
        .into_iter()
        .filter(|diagnostic| diagnostic.is_error())
        .collect::<Vec<_>>();
    if !errors.is_empty() {
        return Err(CrivError::new(format!(
            "reconciliation wrote files but vault validation failed:\n{}",
            errors
                .into_iter()
                .map(|error| error.describe())
                .collect::<Vec<_>>()
                .join("\n")
        )));
    }
    let receipt = Receipt {
        schema: "criv.adr-reconcile/1".into(),
        base_ref: plan.base_ref.clone(),
        target_sha: plan.target_sha.clone(),
        merge_base: plan.merge_base.clone(),
        mappings: plan.mappings.clone(),
        files: receipt_files,
    };
    let contents = serde_json::to_string_pretty(&receipt).map_err(|error| {
        CrivError::new(format!("cannot serialize reconciliation receipt: {error}"))
    })? + "\n";
    write_atomic_in(
        root,
        Path::new(".criv"),
        Path::new(".criv/adr-reconcile.json"),
        &contents,
    )
}

/// A destination can also be another mapping's source. In that case its old
/// contents have already been copied to the later destination, and removing
/// the source would erase the newly published earlier ADR.
fn superseded_paths(mappings: &[Mapping]) -> Vec<&str> {
    let destinations = mappings
        .iter()
        .map(|mapping| mapping.new_path.as_str())
        .collect::<BTreeSet<_>>();
    mappings
        .iter()
        .filter(|mapping| {
            mapping.old_path != mapping.new_path
                && !destinations.contains(mapping.old_path.as_str())
        })
        .map(|mapping| mapping.old_path.as_str())
        .collect()
}

fn rewrite_candidates(root: &Path, plan: &ReconcilePlan) -> Result<BTreeMap<String, String>> {
    let renamed = plan
        .mappings
        .iter()
        .map(|mapping| (mapping.old_path.clone(), mapping.new_path.clone()))
        .collect::<BTreeMap<_, _>>();
    let branch_paths = plan
        .branch_adrs
        .iter()
        .map(|adr| adr.path.clone())
        .collect::<BTreeSet<_>>();
    let mut paths = git::tree_paths(root, "HEAD", ".")?;
    for adr in &plan.branch_adrs {
        if !paths.contains(&adr.path) {
            paths.push(adr.path.clone());
        }
    }
    let mut rewrites = BTreeMap::new();
    for path in paths {
        if path == ".criv/adr-reconcile.json" || path.starts_with(".git/") {
            continue;
        }
        let file = root.join(&path);
        if !file.is_file() {
            continue;
        }
        let contents = match fs::read_to_string(&file) {
            Ok(contents) => contents,
            Err(_) => {
                let bytes = fs::read(&file)?;
                if contains_reference(&bytes, &plan.mappings) {
                    return Err(CrivError::new(format!(
                        "refusing to reconcile binary or non-UTF-8 file `{path}` containing an ADR reference"
                    )));
                }
                continue;
            }
        };
        let is_new =
            branch_paths.contains(&path) || git::blob(root, &plan.merge_base, &path).is_err();
        let rewritten = if is_new {
            rewrite_text(&contents, &plan.mappings, &renamed)
        } else {
            rewrite_owned_lines(
                root,
                &contents,
                &plan.merge_base,
                &path,
                &plan.mappings,
                &renamed,
            )?
        };
        let output_path = renamed.get(&path).cloned().unwrap_or(path);
        if rewritten != contents || output_path != crate::util::strip_prefix(&file, root) {
            rewrites.insert(output_path, rewritten);
        }
    }
    for adr in &plan.branch_adrs {
        if let Some(mapping) = plan
            .mappings
            .iter()
            .find(|mapping| mapping.old_path == adr.path)
        {
            rewrites
                .entry(mapping.new_path.clone())
                .or_insert_with(|| rewrite_text(&adr.contents, &plan.mappings, &renamed));
        }
    }
    Ok(rewrites)
}

fn rewrite_owned_lines(
    root: &Path,
    contents: &str,
    merge_base: &str,
    path: &str,
    mappings: &[Mapping],
    renamed: &BTreeMap<String, String>,
) -> Result<String> {
    let ranges = git::added_lines(root, merge_base, "HEAD", path)?;
    let mut output = String::new();
    for (index, line) in contents.split_inclusive('\n').enumerate() {
        let line_number = index + 1;
        let owned = ranges.iter().any(|range| range.contains(&line_number));
        let rewritten = if owned {
            rewrite_text(line, mappings, renamed)
        } else {
            line.to_owned()
        };
        if !owned && contains_reference(line.as_bytes(), mappings) {
            return Err(CrivError::new(format!(
                "refusing to rewrite target-owned reference in `{path}` line {line_number}"
            )));
        }
        output.push_str(&rewritten);
    }
    Ok(output)
}

fn contains_reference(bytes: &[u8], mappings: &[Mapping]) -> bool {
    mappings.iter().any(|mapping| {
        let id = format!("ADR-{:04}", mapping.old_id);
        let name = Path::new(&mapping.old_path)
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or(&mapping.old_path);
        let stem = name.strip_suffix(".md").unwrap_or(name);
        bytes
            .windows(id.len())
            .any(|window| window == id.as_bytes())
            || bytes
                .windows(mapping.old_path.len())
                .any(|window| window == mapping.old_path.as_bytes())
            || bytes
                .windows(name.len())
                .any(|window| window == name.as_bytes())
            || bytes
                .windows(stem.len())
                .any(|window| window == stem.as_bytes())
    })
}

fn rewrite_text(
    contents: &str,
    mappings: &[Mapping],
    _renamed: &BTreeMap<String, String>,
) -> String {
    let mut text = contents.to_owned();
    for (index, mapping) in mappings.iter().enumerate() {
        let token = format!("__CRIV_ADR_TOKEN_{index}__");
        text = text.replace(&format!("ADR-{:04}", mapping.old_id), &token);
        text = text.replace(&mapping.old_path, &format!("__CRIV_PATH_TOKEN_{index}__"));
        let old_name = Path::new(&mapping.old_path)
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or(&mapping.old_path);
        text = text.replace(old_name, &format!("__CRIV_NAME_TOKEN_{index}__"));
        let old_stem = old_name.strip_suffix(".md").unwrap_or(old_name);
        text = text.replace(old_stem, &format!("__CRIV_STEM_TOKEN_{index}__"));
    }
    for (index, mapping) in mappings.iter().enumerate() {
        text = text.replace(
            &format!("__CRIV_ADR_TOKEN_{index}__"),
            &format!("ADR-{:04}", mapping.new_id),
        );
        text = text.replace(&format!("__CRIV_PATH_TOKEN_{index}__"), &mapping.new_path);
        let new_name = Path::new(&mapping.new_path)
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or(&mapping.new_path);
        text = text.replace(&format!("__CRIV_NAME_TOKEN_{index}__"), new_name);
        let new_stem = new_name.strip_suffix(".md").unwrap_or(new_name);
        text = text.replace(&format!("__CRIV_STEM_TOKEN_{index}__"), new_stem);
    }
    text
}

fn hash(contents: &str) -> String {
    blake3::hash(contents.as_bytes()).to_hex().to_string()
}

fn read_receipt(root: &Path) -> Result<Receipt> {
    serde_json::from_str(&fs::read_to_string(root.join(".criv/adr-reconcile.json"))?).map_err(|_| {
        CrivError::new(
            "ADR reconciliation receipt is malformed; remove it only after recovering the worktree",
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rewrites_overlapping_ids_simultaneously() {
        let mappings = vec![
            Mapping {
                old_id: 5,
                new_id: 7,
                old_path: "docs/adr/0005-a.md".into(),
                new_path: "docs/adr/0007-a.md".into(),
            },
            Mapping {
                old_id: 6,
                new_id: 8,
                old_path: "docs/adr/0006-b.md".into(),
                new_path: "docs/adr/0008-b.md".into(),
            },
        ];
        let paths = mappings
            .iter()
            .map(|mapping| (mapping.old_path.clone(), mapping.new_path.clone()))
            .collect();
        assert_eq!(
            rewrite_text("ADR-0005 ADR-0006 0005-a.md", &mappings, &paths),
            "ADR-0007 ADR-0008 0007-a.md"
        );
    }

    #[test]
    fn retains_a_destination_that_is_another_mapping_source() {
        let mappings = vec![
            Mapping {
                old_id: 5,
                new_id: 7,
                old_path: "docs/adr/0005-a.md".into(),
                new_path: "docs/adr/0007-a.md".into(),
            },
            Mapping {
                old_id: 7,
                new_id: 8,
                old_path: "docs/adr/0007-a.md".into(),
                new_path: "docs/adr/0008-a.md".into(),
            },
        ];
        assert_eq!(superseded_paths(&mappings), vec!["docs/adr/0005-a.md"]);
    }

    #[test]
    fn allocates_branch_adrs_contiguously_in_original_numeric_order() {
        let branch_adrs = vec![
            AdrFile {
                path: "docs/adr/0009-later.md".into(),
                id: 9,
                slug: "later".into(),
                contents: String::new(),
            },
            AdrFile {
                path: "docs/adr/0007-earlier.md".into(),
                id: 7,
                slug: "earlier".into(),
                contents: String::new(),
            },
        ];
        let mappings = allocation_mappings(&branch_adrs, 12, true).unwrap();
        assert_eq!(
            mappings,
            vec![
                Mapping {
                    old_id: 7,
                    new_id: 13,
                    old_path: "docs/adr/0007-earlier.md".into(),
                    new_path: "docs/adr/0013-earlier.md".into(),
                },
                Mapping {
                    old_id: 9,
                    new_id: 14,
                    old_path: "docs/adr/0009-later.md".into(),
                    new_path: "docs/adr/0014-later.md".into(),
                },
            ]
        );
        assert!(
            allocation_mappings(&branch_adrs, 12, false)
                .unwrap()
                .is_empty()
        );
    }

    #[test]
    fn rejects_allocations_past_adr_9999() {
        let branch_adrs = vec![AdrFile {
            path: "docs/adr/0001-topic.md".into(),
            id: 1,
            slug: "topic".into(),
            contents: String::new(),
        }];
        let error = allocation_mappings(&branch_adrs, 9999, true).unwrap_err();
        assert!(error.to_string().contains("ADR-9999"));
    }
}
