use std::fs;
use std::path::Path;

use crate::Result;
use crate::c4_code;
use crate::config::ArchitectureCodeConfig;
use crate::util::read_to_string;
use crate::vault::Vault;

pub(crate) fn write_code_architecture(root: &Path, vault: &Vault) -> Result<bool> {
    let Some(config) = &vault.config.architecture_code else {
        return Ok(false);
    };

    write_code_architecture_with_config(root, vault, config)
}

fn write_code_architecture_with_config(
    root: &Path,
    vault: &Vault,
    config: &ArchitectureCodeConfig,
) -> Result<bool> {
    let path = root.join(&config.output);
    let content = code_architecture_content(vault, config);
    if path.exists() && read_to_string(&path)? == content {
        return Ok(false);
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(true)
}

fn code_architecture_content(vault: &Vault, config: &ArchitectureCodeConfig) -> String {
    if Path::new(&config.output)
        .extension()
        .is_some_and(|ext| ext == "c4")
    {
        code_architecture_artifact(vault)
    } else {
        code_architecture_note(vault, &config.title)
    }
}

fn code_architecture_artifact(vault: &Vault) -> String {
    let diagram = c4_code::for_all_indexed_sources_dot(vault).join("\n");
    format!("// criv:generated true\n{diagram}\n")
}

fn code_architecture_note(vault: &Vault, title: &str) -> String {
    let diagram = c4_code::for_all_indexed_sources_dot(vault).join("\n");
    format!(
        r#"---
id: architecture-code
kind: doc
title: {title}
---

# {title}

This file is generated by `criv watch --once` from all indexed source graph
code. Source scope comes from `[source].roots`, `[source].exclude`, and
`[index].source` in `criv.toml`.

```dot
{diagram}
```
"#
    )
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use tempfile::TempDir;

    use super::*;

    #[test]
    fn code_architecture_write_reports_changed_then_noop() {
        let temp = TempDir::new().unwrap();
        write_architecture_fixture(temp.path(), true);
        let vault = Vault::load(temp.path()).unwrap();

        assert!(write_code_architecture(temp.path(), &vault).unwrap());
        assert!(!write_code_architecture(temp.path(), &vault).unwrap());

        let output = read_to_string(&temp.path().join("docs/architecture/04-code.md")).unwrap();
        assert!(output.contains("id: architecture-code"));
        assert!(output.contains("```dot"));
        assert!(output.contains("\"src/lib.rs#run\" [label=\"run\\nsrc/lib.rs\"]"));
        assert!(output.contains("\"src/lib.rs#helper\" [label=\"helper\\nsrc/lib.rs\"]"));
        assert!(output.contains("\"src/lib.rs#run\" -> \"src/lib.rs#helper\""));
    }

    #[test]
    fn code_architecture_uses_no_indexed_source_message() {
        let temp = TempDir::new().unwrap();
        write_architecture_fixture(temp.path(), false);
        let vault = Vault::load(temp.path()).unwrap();

        assert!(write_code_architecture(temp.path(), &vault).unwrap());

        let output = read_to_string(&temp.path().join("docs/architecture/04-code.md")).unwrap();
        assert!(output.contains("digraph criv_code"));
        assert!(output.contains("// no indexed source files available"));
    }

    #[test]
    fn code_architecture_c4_output_writes_direct_dot() {
        let temp = TempDir::new().unwrap();
        write_architecture_fixture_with_output(temp.path(), true, "docs/architecture/04-code.c4");
        let vault = Vault::load(temp.path()).unwrap();

        assert!(write_code_architecture(temp.path(), &vault).unwrap());
        assert!(!write_code_architecture(temp.path(), &vault).unwrap());

        let output = read_to_string(&temp.path().join("docs/architecture/04-code.c4")).unwrap();
        assert!(output.starts_with("// criv:generated true\ndigraph criv_code"));
        assert!(!output.contains("```dot"));
        assert!(!output.contains("id: architecture-code"));
        assert!(output.contains("\"src/lib.rs#run\" [label=\"run\\nsrc/lib.rs\"]"));
        assert!(output.contains("\"src/lib.rs#run\" -> \"src/lib.rs#helper\""));
    }

    fn write_architecture_fixture(root: &Path, source_index: bool) {
        write_architecture_fixture_with_output(root, source_index, "docs/architecture/04-code.md");
    }

    fn write_architecture_fixture_with_output(root: &Path, source_index: bool, output: &str) {
        fs::create_dir_all(root.join("src")).unwrap();
        fs::create_dir_all(root.join("docs")).unwrap();
        fs::write(
            root.join("criv.toml"),
            format!(
                r#"
[source]
roots = ["src"]

[index]
source = {source_index}

[architecture.code]
output = "{output}"
title = "Code diagram for criv"
"#
            ),
        )
        .unwrap();
        fs::write(
            root.join("src/lib.rs"),
            r#"
fn run() {
    helper();
}

fn helper() {}
"#,
        )
        .unwrap();
    }
}
